singleQuote: true
tabWidth: 2
printWidth: 80
trailingComma: "all"
useTabs: false
semi: true

arrowParens: "avoid"
bracketSpacing: true
htmlWhitespaceSensitivity: "css"

overrides:
  - files: ["*.yml", "*.yaml"]
    options:
      singleQuote: false
  - files: ["*.html"]
    options:
      tabWidth: 4
  - files: ["dockerfile"]
    options:
      useTabs: true
