############################################################################################
############################################################################################
############################################################################################
############# To see current config and options: ###########################################
############# % yarn config -v                   ###########################################
############################################################################################
############################################################################################
############################################################################################

yarnPath: .yarn/releases/yarn-3.2.1.cjs

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

nodeLinker: node-modules
nmSelfReferences: false
nmMode: classic

# changeset
changesetBaseRefs:
  - "master"
  - "origin/master"
  - "upstream/master"
changesetIgnorePatterns:
  - "**/*.test.{js,ts}"

enableTransparentWorkspaces: true

# ui
enableColors: true
enableMessageNames: true

npmRegistries:
  "https://registry.npmjs.org/":
    npmAuthToken: NPM_AUTH_TOKEN
